# Conexión a PostgreSQL XELQA
spring.datasource.url=jdbc:postgresql://localhost:5432/xelqa_db
spring.datasource.username=postgres
spring.datasource.password=03052018MA$

# Hibernate Configuration (validate asegura que tus entidades coincidan con el SQL)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Puerto del Backend
server.port=8080